/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegrasForm.java
 *
 * Created on 12/09/2011, 22:18:02
 */
package br.edu.unijorge.form;

import br.edu.unijorge.util.UtilX;

/**
 *
 * @author Glauber
 */
public class RegrasForm extends DialogForm {

    /** Creates new form RegrasForm */
    public RegrasForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal, DialogForm.LARGURA, DialogForm.ALTURA);
        initComponents();
        UtilX.centerChild(parent, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRegras = new javax.swing.JPanel();
        jspRegras = new javax.swing.JScrollPane();
        jtaRegras = new javax.swing.JTextArea();
        jbFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jspRegras.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspRegras.setEnabled(false);
        jspRegras.setName(""); // NOI18N

        jtaRegras.setColumns(20);
        jtaRegras.setEditable(false);
        jtaRegras.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jtaRegras.setLineWrap(true);
        jtaRegras.setRows(5);
        jtaRegras.setText("-REGRAS\n\n-OBJETIVO DO JOGO\nCada um comanda seu exército, que tem por objetivo capturar a bandeira do exército inimigo. \nUma outra forma de vencer é deixando o adversário sem movimentos legais (derrotando todas as suas peças móveis, por exemplo).\n\n-PEÇAS\nExistem dois tipos de peças: As móveis e as imóveis.\n\nOs exércitos são distintos pelas cores azul e vermelho. As imóveis são uma bandeira e seis bombas.\n\n   * A bandeira deve ficar escondida, pois quando é capturada pelo adversário, o jogo acaba e o que teve sua bandeira capturada perde.\n    *As bombas são peças que derrotam qualquer outra, com exceção do cabo armeiro.\n\nAs peças móveis são usadas para invadir o território adversário, derrotar suas peças e capturar a bandeira, sendo esta, o objetivo do jogo. \nCada uma tem um número, que representa seu poder. Quanto maior o número, mais forte é.\n\n    *Um espião, 1, que é a única peça que pode derrotar o marechal\n    *Oito soldados, 2, que podem mover mais de uma casa por vez, a corrida. Um soldado não pode correr e atacar na mesma vez.\n    *Cinco cabos armeiros, 3, que podem desarmar as bombas.\n    *Quatro sargentos, 4.\n    *Quatro tenentes, 5.\n    *Quatro capitães, 6.\n    *Três majores, 7.\n    *Dois coronéis, 8.\n    *Um general, 9.\n    *Um marechal, 10, que pode ser morto pelo espião.\n\n-O ESPIÃO E O MARECHAL\n\nO espião é a peça mais fraca do jogo, no nível 1, e o marechal a mais forte, no nível 10. \nSe um espião atacar um marechal, este morre, mas se o contrário acontecer, um espião for atacado por um marechal, é aquele que morre. \nOu seja, entre o espião e o marechal, o que atacar vence.");
        jtaRegras.setWrapStyleWord(true);
        jtaRegras.setAutoscrolls(false);
        jtaRegras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jspRegras.setViewportView(jtaRegras);

        javax.swing.GroupLayout jpRegrasLayout = new javax.swing.GroupLayout(jpRegras);
        jpRegras.setLayout(jpRegrasLayout);
        jpRegrasLayout.setHorizontalGroup(
            jpRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspRegras, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jpRegrasLayout.setVerticalGroup(
            jpRegrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspRegras, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );

        jbFechar.setText("Fechar");
        jbFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbFecharMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbFechar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpRegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFecharMouseReleased
        this.dispose();
    }//GEN-LAST:event_jbFecharMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegrasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegrasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegrasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegrasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegrasForm dialog = new RegrasForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbFechar;
    private javax.swing.JPanel jpRegras;
    private javax.swing.JScrollPane jspRegras;
    private javax.swing.JTextArea jtaRegras;
    // End of variables declaration//GEN-END:variables
}
